#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Jan 08, 2023 08:43:10 AM CST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m54" -background #004040 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1365x697+1913+306
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4656 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label "$top.lab47" \
        -activebackground #004040 -activeforeground SystemButtonText \
        -anchor w -background #004040 -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family Arial -size 36 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground #f9ff00 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor #ffff00 -text "Limpiando Texto 4.5" 
    vTcl:DefineAlias "$top.lab47" "Label1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    text "$top.tex48" \
        -background #000000 -font "TkTextFont" -foreground #00ff00 \
        -height 544 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 1338 \
        -wrap word 
    $top.tex48 configure -font "TkTextFont"
    $top.tex48 insert end text
    vTcl:DefineAlias "$top.tex48" "txtCajaTexto" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "📑" 
    vTcl:DefineAlias "$top.but49" "btnCopiar" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "🗑" 
    vTcl:DefineAlias "$top.but50" "btnBorrar" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but51" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "💾" 
    vTcl:DefineAlias "$top.but51" "btnGuardar" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but52" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "🚀" 
    vTcl:DefineAlias "$top.but52" "btnProceso" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but53" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "📁" 
    vTcl:DefineAlias "$top.but53" "btnAbrir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    menu "$top.m54" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background #004040 -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    button "$top.but55" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "🔒" 
    vTcl:DefineAlias "$top.but55" "btnSalir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    entry "$top.ent56" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 1184 
    vTcl:DefineAlias "$top.ent56" "txbDireccionArchivo" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "🔊" 
    vTcl:DefineAlias "$top.but47" "btnLeer" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    entry "$top.ent47" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 534 
    vTcl:DefineAlias "$top.ent47" "txbTextoModificado" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    entry "$top.ent48" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 534 
    vTcl:DefineAlias "$top.ent48" "txbTextoAModificar" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but54" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "+" 
    vTcl:DefineAlias "$top.but54" "btnCambiar" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab47 \
        -in $top -x 0 -relx 0.272 -y 0 -rely 0.014 -width 0 -relwidth 0.347 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.tex48 \
        -in $top -x 0 -relx 0.007 -y 0 -rely 0.086 -width 0 -relwidth 0.98 \
        -height 0 -relheight 0.78 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.918 -y 0 -rely 0.875 -width 47 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.954 -y 0 -rely 0.875 -width 47 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.918 -y 0 -rely 0.933 -width 47 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 0 -relx 0.813 -y 0 -rely 0.875 -width 47 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.881 -y 0 -rely 0.933 -width 47 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.954 -y 0 -rely 0.933 -width 47 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.007 -y 0 -rely 0.947 -width 1184 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.881 -y 0 -rely 0.875 -width 47 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 0 -relx 0.41 -y 0 -rely 0.89 -width 534 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 0 -relx 0.007 -y 0 -rely 0.89 -width 534 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.85 -y 0 -rely 0.875 -width 47 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

